#!/bin/sh
#~./bashrc

FILENAME="whyAnswers.txt"
CHECKNUM='^[0-9]+$'
TOTAL=0
if ! [[ -f "$FILENAME" ]]
then
	echo Error: datafile cannot be found
	exit 2
fi
cat $FILENAME | {
while IFS= read -r LINE
do
	if [[ ${LINE:0:1} = "%" ]]
	then
		((TOTAL=TOTAL+1))
	fi
done
INDEX=-1
if [[ $# == 0 ]]
then
        INDEX=$((RANDOM%TOTAL))
elif [[ $# == 1 ]] && [[ $1 =~ $CHECKNUM ]] && [[ $1 < $TOTAL ]]
then
	INDEX=$1
else
	echo why: invald option -- \'$1\'
	echo Try \'why --help\' for more information.
	exit 1
fi
COUNT=0
cat $FILENAME | while IFS= read -r LINE
do
        FIRSTCHAR="${LINE:0:1}"
	if [[ $FIRSTCHAR == "%" ]]
	then
		((COUNT=COUNT+1))
		if [[ $COUNT > $INDEX ]]
		then
			exit
		fi
	elif [[ $COUNT == $INDEX ]]
	then
		echo "$LINE"
	fi
done
}
