#!/bin/sh
#~./bashrc

############################################################
# help                                                     #
############################################################
help()
{
	# Display Help
	echo "Usage: why [INDEX]"
	echo "Print a quotation from an author about why the E4S Software exists."
	echo
	echo "Options:"
	echo "  -#				an index relating to a certain quote in the datafile;"
	echo "				 the current indexes available are 0-$(($TOTAL-1))"
	echo
	echo "Exit Status:"
	echo " 0  if okay"
	echo " 1  if invalid option is provided"
	echo " 2  if datafile cannot be found"
	echo
}

############################################################
############################################################
# Main program                                             #
############################################################
############################################################
FILENAME="whyAnswers.txt"
CHECKNUM='^[-][0-9]+$'
TOTAL=0
if ! [[ -f "$FILENAME" ]]
then
	echo Error: datafile cannot be found
	exit 2
fi
cat $FILENAME | {
while IFS= read -r LINE
do
	if [[ ${LINE:0:1} = "%" ]]
	then
		((TOTAL=TOTAL+1))
	fi
done
INDEX=-1
if [[ $# == 0 ]]
then
        INDEX=$((RANDOM%TOTAL))
elif [[ $# == 1 ]] && [[ $1 =~ $CHECKNUM ]] && [[ $1 < $TOTAL ]]
then
	INDEX=$1
	((INDEX=0-INDEX))
elif [[ $# == 1 ]] && [[ $1 == "--help" ]]
then
	help
else
	echo why: invald option -- \'$1\'
	echo Try \'why --help\' for more information.
	exit 1
fi
COUNT=0
cat $FILENAME | while IFS= read -r LINE
do
        FIRSTCHAR="${LINE:0:1}"
	if [[ $FIRSTCHAR == "%" ]]
	then
		((COUNT=COUNT+1))
		if [[ $COUNT > $INDEX ]]
		then
			exit
		fi
	elif [[ $COUNT == $INDEX ]]
	then
		echo "$LINE"
	fi
done
}
